---
# Test: backwards-compatible zulip.password field.
zulip:
  password: compat-secret-key
  environment:
    SETTING_ZULIP_ADMINISTRATOR: "admin@example.com"
    SETTING_EXTERNAL_HOST: zulip.example.com
